### PR TITLE
Knights and Knaves puzzle

### PR DESCRIPTION
**Pull request by phelma**
I believe this puzzle originates from [Raymond Smullyan's](https://en.m.wikipedia.org/wiki/Raymond_Smullyan) book _What is the name of this book?_
This one is my favourite, but there are a number of knight and knave puzzles, and a great deal of other puzzles in Smullyan's books, lots of which could feature in this collection of great puzzles.

### CODE REVIEW

**Comment by sharkdp** [comment]
A classic one, thanks! You just inspired me to get out my Smullyan book from the shelf :smile: 

Some comments:
- I think these kinds of puzzles are well-defined if one is only allowed to ask yes/no questions. In this case, it is always clear that the liar will simply negate the correct answer.
- What kind of difficulty should it get? I would rather classify it as medium...
- Is there a source we can link to? We could also cite the book..

**Comment by sharkdp** [comment]
I hope it is okay that I close this, as #5 is of the same type. Thank you very much again.

**Comment by phelma** [comment]
@sharkdp That is fine, although I will point out that although these puzzles are of the same nature, they are very different in difficulty.

The "Three Gods" puzzle is very difficult (_"Hardest logic puzzle ever"_) taking quite some time and almost certainly a pen and paper. Whereas the 'Knights and Knaves' fork in the road puzzle can he solved in a few seconds/minutes without need for much calculations.

**Comment by sharkdp** [comment]
I completely agree. What do you think about adding it as a kind of introduction / first part to the "Three gods" puzzle?

**Comment by pickten** [comment]
In that case, maybe another problem as well to bridge the difficulty gap? e.g. the four brother puzzle, which reads as follows (I don't remember the source, unfortunately, but I don't think it would be too hard to track down):

There are four brothers, one of whom always tells the truth and is correct in his belief, one of whom always tells the truth but is incorrect in his beliefs, one of whom always lies and is correct in his beliefs, and one of whom always lies but is incorrect in his beliefs. While you know this ahead of time, you don't know which brother is which. One of them owns a painting. Your task is to figure out which brother owns the painting in as few yes/no questions as possible.

**Comment by sharkdp** [comment]
@pickten Thank you for the suggestion. The four-brothers puzzle seems to be from R. Smullyan, too. See for example page 30 in "To mock a mockingbird":
https://books.google.de/books?id=6_CcsKjNbzUC&lpg=PP1&hl=de&pg=PP1#v=onepage&q&f=false

I see several options:
1. We add the three puzzles separately in the main list (with different difficulty ratings).
2. We add all of them as a single puzzle which is divided into parts with increasing difficulty.
3. We select only one puzzle of this type (either one of the three mentioned ones or another related puzzle).

After thinking about this again, I would actually prefer the third option. In this case, I would try to find a good medium-difficulty puzzle of this type. I haven't solved the four-brothers puzzle yet, but it looks promising.

But I'm also fine with option 2. I'd rather try to avoid option 1, as these puzzles seem to be of a very similar type.

@phelma @pickten @cruegge What do you think?

**Comment by cruegge** [comment]
I also think that having only one puzzle of a type is the best option, but maybe one could include suitable links to variations.

**Comment by pickten** [comment]
Seeing the similarities, I'd also rather avoid 1, but 2 or 3 are equally fine in my opinion.

Also, with regards to the Four Brothers puzzle, it seems likely to me as well that the source was Smullyan.

**Comment by sharkdp** [comment]
I thought about this a little bit more and came to the conclusion that "Three gods" is probably too hard (compared with the other puzzles here). I now chose to simply include the easiest puzzle of this type and add a reference to the "hardest logic puzzle ever".

@cruegge Thank you very much, anyway!

@pickten @phelma Thanks!

**Pull request merged**
